services:
  app:
    container_name: app
    build: .
    ports:
      - "${PORT}:${PORT}"
    command: >
      bash -c "uvicorn --host 0.0.0.0 --port ${PORT} --reload app.main:app"
    volumes:
      - .:/code
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    env_file:
      - ./.env
    depends_on:
      - kafka

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - '2181:2181'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:latest
    ports:
      - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
